version: "3"
services:
  web:
    depends_on:
      - db
    build:
      context: ./backend
    container_name: ft_transcendence-web
    restart: always
    environment:
      - API_UID_42=${API_UID_42}
      - API_SECRET_42=${API_SECRET_42}
      - API_REDIR_URI_42=${API_REDIR_URI_42}
      - API_HOST_42=${API_HOST_42}
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - 3001:3001 #webserver (change this port on prod)
      - 5555:5555 #prisma studio (change this port on prod)
    networks:
      - ft_trans
    volumes:
      - ./backend:/ft_transcendence-web #maps current host dir to docker working dir

  db:
    image: postgres
    container_name: ft_transcendence-db
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '5432:5432' #database 
    networks:
      - ft_trans
    volumes: 
      - db:/var/lib/postgresql/data

  front:
    depends_on:
      - web
    build:
      context: ./frontend
    container_name: ft_transcendence-front
    ports:
      - 3000:3000 #frontend (change this port on prod)
    networks:
      - ft_trans

    volumes:
      - ./frontend:/ft_transcendence-front #maps current host dir to docker working dir

volumes:
  db:
    driver: local

networks:
  ft_trans:
