#TODO setup postgres db
#TODO env setup
#TODO frontend docker setup

version: "3"
services:
  web:
    depends_on:
      - db
    build:
      context: ./backend
    container_name: ft_transcendence-web
    ports:
      - 3001:3001 #change this port on prod
    networks:
      - ft_trans
    volumes:
      - ./backend:/ft_transcendence-web #maps current host dir to docker working dir

  db:
    image: postgres
    container_name: ft_transcendence-db
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    networks:
      - ft_trans
    volumes: 
      - db:/var/lib/postgresql/data

  front:
    depends_on:
      - web
    build:
      context: ./frontend
    container_name: ft_transcendence-front
    ports:
      - 80:3000 #change this port on prod
    networks:
      - ft_trans

    volumes:
      - ./frontend:/ft_transcendence-front #maps current host dir to docker working dir

volumes:
  db:
    driver: local

networks:
  ft_trans:
